#version 410 core
#pragma debug(on)
#pragma optimize(off)

// Vertex stage for the fullscreen “present” pass.
//
// The CPU has already produced the final image; we only pass through clip-space positions
// generated by Plane (corners at ±1) and forward UVs for texture lookup in the fragment shader.
//
// aNormal is unused here but matches the vertex layout consumed by Mesh (attrib location 1).

layout (location = 0) in vec3 aPosition;
layout (location = 1) in vec3 aNormal;
layout (location = 2) in vec2 aTextureCoords;

out vec2 TexCoords;

void main() {
    TexCoords = aTextureCoords;
    gl_Position = vec4(aPosition, 1.0);
}
